In [18]:
import numpy as np
import pandas as pd

# Checking if the dataset is  imported

In [19]:
movies = pd.read_csv("movie_dataset.csv")

In [20]:
movies["tagline"][14]

'You will believe that a man can fly.'

# Feature Extraction and Cleaning

In [21]:
movies = pd.read_csv("movie_dataset.csv")
l = ['keywords','cast','genres','director']
moviesCLEAN = movies[l]

In [22]:
movies.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [23]:
moviesCLEAN= moviesCLEAN.fillna("")

In [24]:
moviesCLEAN.isnull().sum()

keywords    0
cast        0
genres      0
director    0
dtype: int64

In [25]:
def combined_feature( dataframe, key, coloumnList ):
    dataframe[key]=""
    for i in coloumnList:
        dataframe[key]+=dataframe[i]+" "
        
combined_feature(moviesCLEAN,"cmb",l)

In [26]:
moviesCLEAN["cmb"]

0       culture clash future space war space colony so...
1       ocean drug abuse exotic island east india trad...
2       spy based on novel secret agent sequel mi6 Dan...
3       dc comics crime fighter terrorist secret ident...
4       based on novel mars medallion space travel pri...
                              ...                        
4798    united states\u2013mexico barrier legs arms pa...
4799     Edward Burns Kerry Bish\u00e9 Marsha Dietlein...
4800    date love at first sight narration investigati...
4801     Daniel Henney Eliza Coupe Bill Paxton Alan Ru...
4802    obsession camcorder crush dream girl Drew Barr...
Name: cmb, Length: 4803, dtype: object

# Finding Similarity

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
matrix = CountVectorizer()
out=matrix.fit_transform(moviesCLEAN["cmb"])

In [29]:
print(matrix.get_feature_names())

['11', '15th', '17th', '18th', '1910s', '1917', '1920s', '1930s', '1950s', '1960s', '1970s', '1980s', '1990s', '1992', '1995', '19th', '2001', '2002', '3d', '40', '50', '51', '60s', '66', 'aaliyah', 'aamir', 'aaran', 'aarniokoski', 'aaron', 'aasheekaa', 'aasif', 'abai', 'abandoned', 'abascal', 'abbas', 'abbass', 'abbey', 'abbie', 'abbott', 'abdalla', 'abdoo', 'abduction', 'abdul', 'abdulayev', 'abdullah', 'abe', 'abel', 'abell', 'abercrombie', 'abernathy', 'abhinay', 'abhishek', 'abi', 'abigail', 'abiteboul', 'abkarian', 'able', 'abo', 'abraham', 'abrahams', 'abrahamson', 'abrams', 'abramsohn', 'abroad', 'abu', 'abuse', 'abusive', 'academy', 'accent', 'accepting', 'accident', 'accidental', 'accountant', 'accusal', 'accusations', 'accused', 'ace', 'acharya', 'achrekar', 'acinapura', 'acker', 'ackland', 'ackles', 'ackman', 'acovone', 'acres', 'action', 'activism', 'activist', 'actor', 'actors', 'actress', 'ad', 'ada', 'adam', 'adams', 'adamson', 'adaptation', 'adar', 'addict', 'addicted'

In [30]:
print(out.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [32]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(out)
sim

array([[1.        , 0.10540926, 0.12038585, ..., 0.        , 0.        ,
        0.        ],
       [0.10540926, 1.        , 0.0761387 , ..., 0.03651484, 0.        ,
        0.        ],
       [0.12038585, 0.0761387 , 1.        , ..., 0.        , 0.11145564,
        0.        ],
       ...,
       [0.        , 0.03651484, 0.        , ..., 1.        , 0.        ,
        0.04264014],
       [0.        , 0.        , 0.11145564, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04264014, 0.        ,
        1.        ]])

# Finding the most similar movie

In [35]:
mIndex = 0
while(mIndex < moviesCLEAN.shape[0]):
    if(str(movies["title"][mIndex])=="Avatar"): break
        

In [36]:
mIndex


0

In [37]:
movies["title"][0]


'Avatar'

In [40]:
similarAvatar = sorted(list(enumerate(sim[mIndex])),key= lambda x:x[1] , reverse= True)

In [41]:
similarAvatar


[(0, 1.0000000000000004),
 (94, 0.42339019740572564),
 (2403, 0.3774256780481986),
 (3208, 0.3464101615137755),
 (47, 0.34426518632954817),
 (56, 0.33596842045264647),
 (3158, 0.33333333333333337),
 (2198, 0.31426968052735443),
 (2696, 0.30792014356780045),
 (4401, 0.28867513459481287),
 (1531, 0.2858966759567453),
 (278, 0.2810913475705226),
 (1053, 0.2809003238667948),
 (239, 0.2765204519281134),
 (838, 0.2749859704614352),
 (61, 0.27498597046143514),
 (232, 0.2694301256218254),
 (4332, 0.2694301256218254),
 (661, 0.264197974633739),
 (4593, 0.264197974633739),
 (3730, 0.2592592592592593),
 (1650, 0.2501595914621521),
 (158, 0.24618298195866545),
 (461, 0.24618298195866545),
 (1083, 0.24618298195866542),
 (322, 0.24077170617153845),
 (228, 0.24077170617153842),
 (539, 0.24077170617153842),
 (577, 0.23570226039551587),
 (1990, 0.23570226039551587),
 (1652, 0.23570226039551584),
 (10, 0.23094010767585035),
 (400, 0.23094010767585035),
 (4, 0.23094010767585033),
 (2129, 0.23094010767585

In [43]:
print("Top 5 movies similar to Avatar are:")
for i in range(1,6):
    print(movies["title"][similarAvatar[i][0]])

Top 5 movies similar to Avatar are:
Guardians of the Galaxy
Aliens
Star Wars: Clone Wars: Volume 1
Star Trek Into Darkness
Star Trek Beyond
